apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: glance
  keystoneEndpoint: api1
  glanceAPIs:
    api1:
      preserveJobs: false
      replicas: 1
      type: single
    api2:
      preserveJobs: false
      replicas: 1
      type: single
  secret: osp-secret
  storageClass: local-storage
  storageRequest: 10G
