apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: glance
  keystoneEndpoint: api1
  glanceAPIs:
    api1:
      debug:
        service: false
      preserveJobs: false
      replicas: 1
    api2:
      debug:
        service: false
      preserveJobs: false
      replicas: 1
  secret: osp-secret
  storageClass: local-storage
  storageRequest: 10G
