# Inject inject_metadata config
apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  customServiceConfig: |
    [image_import_opts]
    image_import_plugins = [inject_image_metadata]
    [inject_metadata_properties]
    ignore_user_roles = admin,user1
    inject = "property1":"value1","property2":"value2"
