# permissions for end users to edit glances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glance-editor-role
rules:
- apiGroups:
  - glance.openstack.org
  resources:
  - glances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - glance.openstack.org
  resources:
  - glances/status
  verbs:
  - get
