# permissions for end users to edit glanceapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glanceapi-editor-role
rules:
- apiGroups:
  - glance.openstack.org
  resources:
  - glanceapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - glance.openstack.org
  resources:
  - glanceapis/status
  verbs:
  - get
