apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: glance-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: GlanceAPI is the Schema for the glanceapis API
      displayName: Glance API
      kind: GlanceAPI
      name: glanceapis.glance.openstack.org
      version: v1beta1
  description: Glance Operator
  displayName: Glance Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openstack
  - cn-openstack
  links:
  - name: Glance Operator
    url: https://github.com/openstack-k8s-operators/glance-operator
  maturity: alpha
  provider:
    name: Red Hat
    url: https://redhat.com
  version: 0.0.0
