apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-import-staging-workspace
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
