apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
  namespace: openstack
spec:
  serviceUser: glance
  containerImage: quay.io/podified-antelope-centos9/openstack-glance-api:current-podified
  databaseInstance: openstack
  databaseUser: glance
  glanceAPI:
    containerImage: quay.io/podified-antelope-centos9/openstack-glance-api:current-podified
    type: "single"
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  secret: osp-secret
  storageClass: local-storage
  storageRequest: 10G
