apiVersion: glance.openstack.org/v1beta1
kind: GlanceAPI
metadata:
  name: glanceapi
spec:
  serviceUser: glance
  containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseUser: glance
  databaseHostname: glance
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  replicas: 1
  storageRequest: 10G
  secret: glance-secret
