apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  containerImage: quay.io/podified-antelope-centos9/openstack-glance-api:current-podified
  databaseInstance: openstack
  databaseUser: glance
  glanceAPIInternal:
    containerImage: quay.io/podified-antelope-centos9/openstack-glance-api:current-podified
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  glanceAPIExternal:
    containerImage: quay.io/podified-antelope-centos9/openstack-glance-api:current-podified
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  secret: osp-secret
  storageClass: ""
  storageRequest: 10G
  quotas:
    imageSizeTotal: 1000
    imageStageTotal: 1000
    imageCountUpload: 100
    imageCountTotal: 100
