apiVersion: glance.openstack.org/v1beta1
kind: GlanceAPI
metadata:
  name: glanceapi-sample
spec:
  # Add fields here
  databaseHostname: bar
  databasePassword: bar
  replicas: 1
  storageClass: host-nfs-storageclass
  storageRequest: 10G
