apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  databaseInstance: openstack
  databaseUser: glance
  customServiceConfig: |
    [DEFAULT]
    debug = true
  glanceAPI:
    type: "single"
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  secret: osp-secret
  storageClass: local-storage
  storageRequest: 10G
