# Requires a running swift service and the credentials to access it
# should be in a secret called osp-glance-swift-secret (in our case
# it's in glance-swift-secret.yaml).
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  glance:
    template:
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = default_backend:swift
        [glance_store]
        default_backend = default_backend
        [default_backend]
        swift_store_create_container_on_put = True
        swift_store_auth_version = 3
        swift_store_auth_address = http://keystone-public-openstack.apps-crc.testing
      customServiceConfigSecrets:
        - osp-glance-swift-secret
      databaseInstance: openstack
      glanceAPIInternal:
        debug:
          service: false
        preserveJobs: false
        replicas: 1
      glanceAPIExternal:
        debug:
          service: false
        preserveJobs: false
        replicas: 1
      storageClass: ""
      storageRequest: 1G
