# Define the "osp-glance-swift-secret" Secret that contains sensitive
# information pertaining to the swift backend
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: glance
  name: osp-glance-swift-secret
type: Opaque
stringData:
  swift-secrets.conf: |
    [default_backend]
    swift_store_key = 12345678
    swift_store_user = service:glance
