apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  keystoneEndpoint: default
  glanceAPIs:
    default:
      debug:
        service: false
      preserveJobs: false
      replicas: 1
  storageClass: local-storage
  storageRequest: 10G
